# Generated by Django 4.0.4 on 2022-05-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='检测完成时间')),
                ('re0', models.IntegerField(verbose_name='正常数量')),
                ('re1', models.IntegerField(verbose_name='边瑕疵数量')),
                ('re2', models.IntegerField(verbose_name='角瑕疵数量')),
                ('re3', models.IntegerField(verbose_name='白色点瑕疵数量')),
                ('re4', models.IntegerField(verbose_name='浅色块瑕疵数量')),
                ('re5', models.IntegerField(verbose_name='深色点瑕疵数量')),
                ('re6', models.IntegerField(verbose_name='光圈瑕疵数量')),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=50, unique=True, verbose_name='图片名')),
                ('pic', models.ImageField(upload_to='', verbose_name='图片')),
                ('result', models.IntegerField(choices=[(0, '无瑕疵'), (1, '边异常'), (2, '角异常'), (3, '白色点瑕疵'), (4, '浅色块瑕疵'), (5, '深色点瑕疵'), (6, '光圈瑕疵')], default=0, verbose_name='检测结果')),
                ('the_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
        ),
    ]
