# Generated by Django 4.0.4 on 2022-05-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_events_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='the_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', to_field='user_name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(unique=True, verbose_name='检测完成时间'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='the_events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events', to_field='time'),
        ),
    ]
