# Generated by Django 4.0.4 on 2022-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_events_the_user_alter_events_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DateTimeField(unique=True, verbose_name='检测时间'),
        ),
    ]
