# Generated by Django 4.0.4 on 2022-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(max_length=50, verbose_name='图片名'),
        ),
    ]
