# Generated by Django 4.0.4 on 2022-05-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_picture_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic',
        ),
    ]
